/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.io.IOException;
import java.math.RoundingMode;
import java.net.URL;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.border.Border;
import projetinfo.Orders;

/**
 *
 * @author Gaëtan
 */
public class OrdersPaymentAndPrice extends javax.swing.JPanel
{

    public OrdersPaymentAndPrice(ArrayList<Orders> myOrders)
    {
        initComponents();
        priceValue = new JButton();
        price.add(priceValue, BorderLayout.CENTER);
        
        setLayout(new FlowLayout());
        price();
        totalPrice(myOrders);
        commanderButton();
        setPreferredSize(new Dimension(900, 200));
        

    }

    public JButton getCommander()
    {
        return commander;
    }

    public void totalPrice(ArrayList<Orders> myOrders)
    {
        double totalPrice = 0;

        for (int i = 0; i < myOrders.size(); i++)
            totalPrice = totalPrice + myOrders.get(i).getPrice();

        DecimalFormat df = new DecimalFormat("#.##");
        df.setRoundingMode(RoundingMode.HALF_UP);
        String stringPrice = df.format(totalPrice);

        char[] myPrice = stringPrice.toCharArray();
        for (int j = 0; j < myPrice.length; j++)
            if (myPrice[j] == ',')
                myPrice[j] = '.';

        totalPrice = Double.parseDouble(String.copyValueOf(myPrice));
        Font font = new Font("Courier", Font.BOLD, 26);
        priceValue.setFont(font);
        priceValue.setText("  PRIX TOTAL: " + totalPrice + "€");
        priceValue.setOpaque(false);
        priceValue.setContentAreaFilled(false);
        priceValue.setBorderPainted(false);
        priceValue.setBorder(null);
        priceValue.setForeground(Color.WHITE);
        priceValue.setHorizontalAlignment(JTextField.CENTER);
    }

    public void commanderButton()
    {
        String imageURL = "https://i.goopics.net/aW8RG.jpg";
        Image image = null;

        try
        {
            URL url = new URL(imageURL);
            Image imageBeforeResize = ImageIO.read(url);
            image = imageBeforeResize.getScaledInstance(290, 70, Image.SCALE_SMOOTH);
        } catch (IOException error)
        {
            System.out.println("Erreur searchBarMainPage");
        }

        JLabel label;
        if (image != null)
            label = new JLabel(new ImageIcon(image));
        else
            label = new JLabel();

        commander.setOpaque(false);
        commander.setContentAreaFilled(false);
        commander.setBorderPainted(false);
        commander.add(label);
        revalidate();
        repaint();
    }

    public void price()
    {
        String imageURL = "https://i.goopics.net/dWxOJ.jpg";
        Image image = null;

        try
        {
            URL url = new URL(imageURL);
            Image imageBeforeResize = ImageIO.read(url);
            image = imageBeforeResize.getScaledInstance(290, 70, Image.SCALE_SMOOTH);
        } catch (IOException error)
        {
            System.out.println("Erreur searchBarMainPage");
        }

        JLabel label;
        if (image != null)
            label = new JLabel(new ImageIcon(image));
        else
            label = new JLabel();

        price.setOpaque(false);
        price.setContentAreaFilled(false);
        price.setBorderPainted(false);
//        price.setBorder(null);
        price.add(label);
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        commander = new javax.swing.JButton();
        price = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        commander.setText("Commander");
        add(commander, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 11, 420, 100));

        price.setText("Price");
        add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 11, 415, 100));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton commander;
    private javax.swing.JButton price;
    // End of variables declaration//GEN-END:variables
    private JButton priceValue;
}
