/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Image;
import java.io.IOException;
import java.math.RoundingMode;
import java.net.URL;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import Model.Orders;

/**
 *
 * Button to validate and to order
 */
public class OrdersPaymentAndPrice extends javax.swing.JPanel
{

    public OrdersPaymentAndPrice(ArrayList<Orders> myOrders)
    {
        initComponents();
        priceValue = new JButton();
        price.add(priceValue, BorderLayout.CENTER);
        setLayout(new FlowLayout());
        price();
        totalPrice(myOrders);
        commanderButton();
        setPreferredSize(new Dimension(900, 200));
    }

    // Getter button
    public JButton getCommander()
    {
        return commander;
    }

    // Total price of the current order
    public void totalPrice(ArrayList<Orders> myOrders)
    {
        double totalPrice = 0;

        for (int i = 0; i < myOrders.size(); i++)
            totalPrice = totalPrice + myOrders.get(i).getPrice();

        DecimalFormat df = new DecimalFormat("#.##");
        df.setRoundingMode(RoundingMode.HALF_UP);
        String stringPrice = df.format(totalPrice);

        char[] myPrice = stringPrice.toCharArray();
        for (int j = 0; j < myPrice.length; j++)
            if (myPrice[j] == ',')
                myPrice[j] = '.';

        totalPrice = Double.parseDouble(String.copyValueOf(myPrice));
        Font font = new Font("Courier", Font.BOLD, 26);
        priceValue.setFont(font);
        priceValue.setText("  PRIX TOTAL: " + totalPrice + "€");
        priceValue.setOpaque(false);
        priceValue.setContentAreaFilled(false);
        priceValue.setBorderPainted(false);
        priceValue.setBorder(null);
        priceValue.setForeground(Color.WHITE);
        priceValue.setHorizontalAlignment(JTextField.CENTER);
    }

    // Image of order
    public void commanderButton()
    {
        String imageURL = "https://i.goopics.net/aW8RG.jpg";
        Image image = null;

        try
        {
            URL url = new URL(imageURL);
            Image imageBeforeResize = ImageIO.read(url);
            image = imageBeforeResize.getScaledInstance(290, 70, Image.SCALE_SMOOTH);
        } catch (IOException error)
        {
            System.out.println("Erreur searchBarMainPage");
        }

        JLabel label;
        if (image != null)
            label = new JLabel(new ImageIcon(image));
        else
            label = new JLabel();

        commander.setOpaque(false);
        commander.setContentAreaFilled(false);
        commander.setBorderPainted(false);
        commander.add(label);
        revalidate();
        repaint();
    }


    // Image of price button
    public void price()
    {
        String imageURL = "https://i.goopics.net/dWxOJ.jpg";
        Image image = null;

        try
        {
            URL url = new URL(imageURL);
            Image imageBeforeResize = ImageIO.read(url);
            image = imageBeforeResize.getScaledInstance(290, 70, Image.SCALE_SMOOTH);
        } catch (IOException error)
        {
            System.out.println("Erreur searchBarMainPage");
        }

        JLabel label;
        if (image != null)
            label = new JLabel(new ImageIcon(image));
        else
            label = new JLabel();

        price.setOpaque(false);
        price.setContentAreaFilled(false);
        price.setBorderPainted(false);
        price.add(label);
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        commander = new javax.swing.JButton();
        price = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        commander.setText("Commander");

        price.setText("Price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(commander, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(commander, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton commander;
    private javax.swing.JButton price;
    // End of variables declaration//GEN-END:variables
    private JButton priceValue;
}
